### ISSUE TITLE
Multiline does not grow TextInput. The toolbar / composer height is always fixed. 

### ISSUE THREAD

**Issue by claudiozam** [FaridSafi/react-native-gifted-chat#2287]
#### Issue Description

The toolbar / composer height is always fixed. The auto grow is not working when i am writing multiples lines.

#### Steps to Reproduce / Code Snippets

Write multiple lines in the input field

<img width="421" alt="image" src="https://user-images.githubusercontent.com/2105644/194157835-28507725-cc59-4ce3-a249-22815a692bb2.png">

<img width="427" alt="image" src="https://user-images.githubusercontent.com/2105644/194154445-e6f0c94d-0f1c-4c4b-8591-4c6dc6826981.png">

The same issue can be reproduced with the current example

https://github.com/FaridSafi/react-native-gifted-chat/tree/master/example

#### Expected Results

The toolbar / composer height must grow automatically

<img width="389" alt="image" src="https://user-images.githubusercontent.com/2105644/194154577-cf349158-5522-4313-b48f-04fe652fdbc8.png">

In react-native-gifted-chat version 0.16.3 works ok

#### Additional Information

* Nodejs version: v18.9.1
* React version: 17.0.2
* React Native version: 0.68.3
* react-native-gifted-chat version: 1.0.4
* Platform(s) (iOS, Android, or both?): both

**Comment by jeet-mehta** [comment]
Have you found any solutions for this issue as I am also facing this same issue

**Comment by claudiozam** [comment]
@jeet-mehta for the moment a **temporary** solution is to downgrade to version **0.16.3**

**Comment by mariomurrent-softwaresolutions** [comment]
@claudiozam Whats that label bar at the top?

**Comment by claudiozam** [comment]
@mariomurrent-softwaresolutions custom labels that allows you to filter conversations (chats) like gmail. Is not part of react-native-gifted-chat. With or without them the issue persist.

**Comment by mariomurrent-softwaresolutions** [comment]
Ah okay, I thought it's part, because I'm having the same space above the chat but empty and with white background

**Comment by claudiozam** [comment]
@mariomurrent-softwaresolutions check this issue https://github.com/FaridSafi/react-native-gifted-chat/issues/2220

**Comment by mariomurrent-softwaresolutions** [comment]
@claudiozam Ah thank you - I was already searching for it, but did not find anything. Thx.
And good luck on your issue :)

**Comment by azzadrood** [comment]
Having the same issue

**Comment by wjb8** [comment]
Still having this issue on 1.0.4. I can't revert to 0.16.3 because it causes freezing in my app with the version of RN I'm using. Any updates on this?

**Comment by MUZAFFAR-PURELOGICS** [comment]
Composer height is fixed. Kindly resolve this problem.
![Screenshot 2022-12-15 at 10 11 34 PM](https://user-images.githubusercontent.com/85747798/207924338-dd66c9d7-f978-4df1-8130-0bb9f6ef2cd8.png)
[](url) #

**Comment by flodev** [comment]
hi,

I've created a pull request that will fix this issue here https://github.com/FaridSafi/react-native-gifted-chat/pull/2323

if you want to use patch it in version 1.1.0 i've also created a patch that you can use with npm patch-package.

https://gist.github.com/flodev/3ede2fafc3d238526ffa2d9f3a44d84b

**Comment by nickbuc1** [comment]
I updated to 1.1.0 and I am still having the issue on ios.
I have been playing around with different values but even when commenting everything out, the height of the InputText box does not grow with multiple lines of text.
Any suggestion on how to fix it?
 
`<GiftedChat
                    messages={this.state.messages}
                    user={this.state.currentUser}

                    onSend={newMessage => this.handleSend(newMessage)}
                    alwaysShowSend

                    // To avoid that Gifted limits the height of the window on ios 
                    wrapInSafeArea={false}

                    renderBubble={this.renderBubble}
                    showUserAvatar={true}

                    renderLoading={this.renderLoading}
                    renderSend={this.renderSend}
                    textInputStyle={styles.textInputStyle}
                    multiline
                    /*
                    renderInputToolbar={(props) => (
                        <InputToolbar
                          {...props}
                          containerStyle={styles.textInputToolbarStyle}
                        />
                    )}          
                    */

                    bottomOffset={80}
                    //minComposerHeight={44}
                    //minInputToolbarHeight={35}
                    //maxComposerHeight={150}
                />`

**Comment by flodev** [comment]
hi @nickbuc1,
you need to wait for a newer version.
1.1.0 was released in december. this PR was merged to master branch 5 days ago.
if you want to use it with npm you could reference the github url with the [master branch like so](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#git-urls-as-dependencies)

**Comment by Johan-dutoit** [comment]
I'll release this now.

**Comment by claudiozam** [comment]
Hi, i tested the new release v1.1.1. It works ok, but the input grow super slow now (Compared with 0.16.3).  

Additional Information
Nodejs version: v18.9.1
React version: 18.2.0
React Native version: 0.71.1
react-native-gifted-chat version: 1.1.1
Platform(s) (iOS, Android, or both?): both

**Comment by claudiozam** [comment]
@flodev thanks for your time and contribution. If you have "time" check this new issue https://github.com/FaridSafi/react-native-gifted-chat/issues/2337 related to your commit.

**Comment by abdullahSolace** [comment]
here is the solution https://github.com/FaridSafi/react-native-gifted-chat/issues/1727#issuecomment-2986842248
