### ISSUE TITLE
Edge-to-edge support

### ISSUE THREAD

**Issue by zoontek** [FaridSafi/react-native-gifted-chat#2606]
👋 Hi there!

I'm working on supporting [edge-to-edge layout](https://developer.android.com/develop/ui/views/layout/edge-to-edge) across the entire React Native ecosystem, as it is [enforced on Android 15+](https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge) when targeting SDK level 35 (introduced in [react native 0.77](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0770)).

To prevent library authors from implementing their own edge-to-edge solutions—which could interfere with other libraries—and because it’s not possible to reliably detect if edge-to-edge is already enabled on Android, we collaborated with Expo to create a dedicated library: [react-native-edge-to-edge](https://github.com/zoontek/react-native-edge-to-edge). It can be detected using a simple helper: [react-native-is-edge-to-edge](https://github.com/zoontek/react-native-edge-to-edge/tree/main/react-native-is-edge-to-edge).

Since its release, we've added edge-to-edge support to several React Native libraries:

- react-native-keyboard-controller: [#660](https://github.com/kirillzyusko/react-native-keyboard-controller/pull/660) / [#765](https://github.com/kirillzyusko/react-native-keyboard-controller/pull/765)
- react-native-bootsplash: [6.2.0 release](https://github.com/zoontek/react-native-bootsplash/releases/tag/6.2.0)
- react-native-bottom-tabs: [#97](https://github.com/callstackincubator/react-native-bottom-tabs/issues/97) / [Docs](https://callstackincubator.github.io/react-native-bottom-tabs/docs/guides/edge-to-edge-support.html)
- react-native-true-sheet: [#103](https://github.com/lodev09/react-native-true-sheet/pull/103)
- react-native-unistyles: [Discussion #342](https://github.com/jpudysz/react-native-unistyles/discussions/342)
- expo-router: [#32854](https://github.com/expo/expo/pull/32854)
- expo-status-bar / expo-navigation-bar: [#34478](https://github.com/expo/expo/pull/34478)
- react-native-reanimated: [#6732](https://github.com/software-mansion/react-native-reanimated/pull/6732)
- react-native-avoid-softinput: [#219](https://github.com/mateusz1913/react-native-avoid-softinput/pull/219)
- react-native-screens: [#2464](https://github.com/software-mansion/react-native-screens/pull/2464) _(not merged yet)_
- galeria: [#18](https://github.com/nandorojo/galeria/pull/18)

It has also been integrated into apps like:

- Bluesky: [#7497](https://github.com/bluesky-social/social-app/pull/7497) _(not merged yet)_

### 🤔 Why this issue?

As it's difficult for me to test every React Native library under all possible configurations, I’m opening issues to raise awareness and invite you to try adding `react-native-edge-to-edge` to your example app to verify that everything works correctly on your end. If:

1️⃣ **Your library already supports edge-to-edge**  
👉 Feel free to close this issue—sorry for the inconvenience!

2️⃣ **You'd like to add support**  
👉 Refer to the documentation and the PRs linked above, and feel free to ask me **anything**!

**Comment by ravindra-encoresky** [comment]
@FaridSafi 
Till we get the support for this, we're facing issue in android 15 while updating to sdk 35.
Can we get a patch for it?

![Image](https://github.com/user-attachments/assets/73508427-b1ba-4e1b-ad36-08faa7899cbf)

**Comment by zoontek** [comment]
@ravindra-encoresky I'm not the library author, it's @FaridSafi

**Comment by ravindra-encoresky** [comment]
> [@ravindra-encoresky](https://github.com/ravindra-encoresky) I'm not the library author, it's [@FaridSafi](https://github.com/FaridSafi)

And update for all those facing this issue : **updating the library above 2.8.1** and adding **react-native-keyboard-controller** fixed this issue.

**Comment by kesha-antonov** [comment]
Should be fixed in master

Please also use https://github.com/AppAndFlow/react-native-safe-area-context

**Comment by eisodev-r** [comment]
> Should be fixed in master
> 
> Please also use https://github.com/AppAndFlow/react-native-safe-area-context

2.9.0-alpha.0?

https://github.com/FaridSafi/react-native-gifted-chat/issues/2660#issuecomment-3558965440 <- If I add those two props to keyboardprovider I get edge to edge correctly.

Will it solve this issue (should be green but turns white when using gifted chat from the Keyboardprovider thing) to update to 2.9.0-alpha.0? I tried but didn't manage it to build on Android even with full clean install (see below red pic). **React native 0.81.5 old arch.**

<img width="1450" height="630" alt="Image" src="https://github.com/user-attachments/assets/36621ded-7864-4b21-95a6-58bcb2a487ce" />

<img width="1536" height="1362" alt="Image" src="https://github.com/user-attachments/assets/7c52aa50-bda3-4f69-bc21-6813c2d72062" />

<img width="488" height="894" alt="Image" src="https://github.com/user-attachments/assets/7152b351-7b9e-474e-9ba6-8dbcf7e18efe" />

What should we do to handle this? What is the proper/safe way?

**Comment by eisodev-r** [comment]
> > [@ravindra-encoresky](https://github.com/ravindra-encoresky) I'm not the library author, it's [@FaridSafi](https://github.com/FaridSafi)
> 
> And update for all those facing this issue : **updating the library above 2.8.1** and adding **react-native-keyboard-controller** fixed this issue.

2.8.2-alpha.6 still happening with latest react-native-keyboard-controller 1.19.6 installed on my side.

"react-native-keyboard-controller": "^1.19.5", is used in package.json for 2.8.2-alpha.6.

See my comment here: https://github.com/FaridSafi/react-native-gifted-chat/issues/2660#issuecomment-3558965440
It has no effect on 2.8.1 but works on 2.8.2-alpha.6 with these props set.

**Comment by kesha-antonov** [comment]
I didn't have time to properly test on android. If somebody have time please do it and suggest fixes to code

**Comment by kesha-antonov** [comment]
Removed react-native-keyboard-controller from master

**Comment by kesha-antonov** [comment]
Fixed in master

https://github.com/user-attachments/assets/f64d8512-5985-4cb2-99f2-e02efc1db69c
