### ISSUE TITLE
Empty MessageContainer on Android

### ISSUE THREAD

**Issue by jsoendermann** [FaridSafi/react-native-gifted-chat#486]
#### Issue Description

If I run the example code from the readme (not the advanced example), it works fine on iOS but on Android, none of the Bubbles get displayed.

#### Steps to Reproduce / Code Snippets

Run the example

#### Expected Results

Message Bubbles should appear.

#### Additional Information

* React Native version: 0.45.1
* react-native-gifted-chat version: 0.14.1
* Platform(s) (Android): 7.0

**Comment by jsoendermann** [comment]
Ok, I've tracked the problem down to the InvertibleScrollView that's used in the MessageContainer. If I comment out `renderScrollComponent={this.renderScrollComponent}` at the bottom of MessageContainer.js, the messages show up, albeit at the top of the View.

**Comment by bartolkaruza** [comment]
Hi, the issue is with the inversion used by the https://github.com/expo/react-native-invertible-scroll-view library, caused by an underlying RN issue, which should be fixed in some upcoming React Native release; https://github.com/facebook/react-native/pull/14646

If you need a quick fix now, you can point the dependency for react-native-invertible-scroll-view to "immidi/react-native-invertible-scroll-view#feature/perspective-fix".

**Comment by brunocascio** [comment]
@jsoendermann Could you test again with the latest version published today? (v0.2.8)

**Comment by jsoendermann** [comment]
Hi @brunocascio, it still doesn't seem to be working for me unless I use @bartolkaruza's fix.

**Comment by brunocascio** [comment]
Hi @jsoendermann. I'll be looking at that PR. However, I labeled this issue as a bug.

Thanks for your feedback!

**Comment by bartolkaruza** [comment]
Hi a fix in the underlying animation view logic on Android has been released as part of React Native 0.49.x This issue should be fixed by upgrading your RN version to 0.49 or higher
