### ISSUE TITLE
Message not displaying in huawei P9

### ISSUE THREAD

**Issue by rhenmark** [FaridSafi/react-native-gifted-chat#536]
This package is great but somehow the messages are not displaying on some devices, one of it is the huawei P9. We are using the current version of react native and the gifted chat. Can someone help me how to fix it and explain why is it happening?

**Comment by NSulik** [comment]
I have encountered the exact same issue on multiple Huawei devices (unfortunately I don't have access to the devices myself).

Without access to a device it's very hard for me to debug. I'd love to get more information.

**Comment by urska19** [comment]
I found the same problem on Huawei P10 Lite. It looks like it is Huawei and Android 7 problem. This [issue](https://github.com/expo/react-native-invertible-scroll-view/issues/47) and [fix](https://github.com/expo/react-native-invertible-scroll-view/pull/46) in `InvertibleScrollView.js` helped. Now messages are displaying as expected.

**Comment by abeltje1** [comment]
This issue still is in the GC repo, I think it's because GC is still depending on RN invertible-scroll-view 1.0.0. @FaridSafi could you maybe look into this? It's a real problem for everyone developing GC, especially because it's an issue you'll only encounter on a Huawei, which a lot of developers don't have at hand while developing. This causes awkward encounters with clients when they do have a Huawei.. 

I think (testing now) that the only thing that should be done is update the dependency of RN invertible-scroll-view, so that shouldn't be too much of an issue. Maybe I'm completely wrong though, @urska19 @rhenmark how did you guys solve it?

Cheers!

**Comment by urska19** [comment]
@abeltje1 I am using react 0.44 and what I did to resolve the issue is following. I changed `InvertibleScrollView.js` file as it is suggested in this [fix](https://github.com/expo/react-native-invertible-scroll-view/pull/46/files). And the problem is now resolved.

**Comment by brunocascio** [comment]
Fixed on v0.2.8

**Comment by maraujop** [comment]
@brunocascio Version 0.2.8 doesn't fix the issue in Huawei. It doesn't use a version of react-native-invertible-scroll-view that contains the necessary fix. 

I'm using a fork of react-native-gifted-chat pointing to a fork of react-native-invertible-scroll-view https://github.com/maraujop/react-native-gifted-chat/commits/fix/huawei that makes the trick

**Comment by alizbazar** [comment]
This issue is fixed upon upgrading to react native 0.49.
